{"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","update":{"10.04":[{"package":"python-django","version":"1.1.1-2ubuntu1.9"}],"12.10":[{"package":"python-django","version":"1.4.1-2ubuntu0.4"}],"13.04":[{"package":"python-django","version":"1.4.5-1ubuntu0.1"}],"12.04":[{"package":"python-django","version":"1.3.1-4ubuntu1.8"}]},"usn":"USN-1967-1","info":"python-django vulnerabilities","date":"September 24, 2013","threat":["A remote attacker could use this issue to consume resources, resulting in a denial of service.","An attacker could use this issue to read arbitrary files.","An attacker could possibly use this issue to perform a cross-site scripting attack.."],"CVEs":["CVE-2013-1443","CVE-2013-4315"]}