{"update":{"12.10":[{"package":"python-keystone","version":"2012.2.1-0ubuntu1.2"}],"12.04":[{"package":"python-keystone","version":"2012.1+stable~20120824-a16a0ab9-0ubuntu2.5"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","usn":"USN-1730-1","date":"February 20, 2013","info":"keystone vulnerabilities","threat":["A remote unauthenticated attacker could exploit this to cause a denial of service via resource exhaustion."],"CVEs":["CVE-2013-0282","CVE-2013-1664","CVE-2013-1665"]}