{"date":"January 12, 2015","usn":"USN-2461-3","CVEs":["CVE-2014-9130"],"info":"pyyaml vulnerability","special":"The problem can be corrected by updating your system to the following package versions:\nAfter a standard system update you need to restart applications using\nPyYAML to make all the necessary changes.","threat":["An attacker could create specially crafted YAML data to trigger an assert, causing a denial of service.."],"update":{"12.04":[{"package":"python-yaml","version":"3.10-2ubuntu0.1"},{"version":"3.10-2ubuntu0.1","package":"python3-yaml"}],"14.10":[{"version":"3.11-1ubuntu0.1","package":"python-yaml"},{"package":"python3-yaml","version":"3.11-1ubuntu0.1"}],"14.04":[{"version":"3.10-4ubuntu0.1","package":"python-yaml"},{"package":"python3-yaml","version":"3.10-4ubuntu0.1"}]}}