{"date":"October 01, 2013","special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","update":{"12.10":[{"version":"3.3.0-1ubuntu0.1","package":"python3.3"},{"package":"python3.3-minimal","version":"3.3.0-1ubuntu0.1"}],"13.04":[{"version":"3.3.1-1ubuntu5.2","package":"python3.3"},{"version":"3.3.1-1ubuntu5.2","package":"python3.3-minimal"}]},"usn":"USN-1985-1","CVEs":["CVE-2013-2099","CVE-2013-4238"],"threat":["An attacker could exploit this to cause Python to consume resources, resulting in a denial of service.","An attacker could exploit this to perform a man in the middle attack to view sensitive information or alter encrypted communications."],"info":"python3.3 vulnerabilities"}