{"date":"May 15, 2014","CVEs":["CVE-2014-1418"],"info":"python-django vulnerabilities","usn":"USN-2212-1","threat":["An attacker may use this to retrieve private data or poison caches.","An attacker may use this to cause unexpected redirects."],"special":"The problem can be corrected by updating your system to the following package versions:\nAfter a standard system update you need to restart Django applications to\nmake all the necessary changes.","update":{"12.04":[{"version":"1.3.1-4ubuntu1.11","package":"python-django"}],"10.04":[{"version":"1.1.1-2ubuntu1.12","package":"python-django"}],"12.10":[{"package":"python-django","version":"1.4.1-2ubuntu0.7"}],"13.10":[{"package":"python-django","version":"1.5.4-1ubuntu1.3"}],"14.04":[{"package":"python-django","version":"1.6.1-2ubuntu0.3"}]}}