{"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","threat":["An authenticated attacker could exploit this to obtain sensitive information in private flavors.","A remote unauthenticated attacker could exploit this using the Nova API to cause a denial of service via resource exhaustion.","An authenticated attacker could exploit this to cause a denial of service.","An authenticated attacker could exploit this to cause a denial of service on the compute node running the instance."],"update":{"13.04":[{"version":"1:2013.1.3-0ubuntu1.1","package":"python-nova"}],"12.04":[{"package":"python-nova","version":"2012.1.3+stable-20130423-e52e6912-0ubuntu1.2"}],"12.10":[{"package":"python-nova","version":"2012.2.4-0ubuntu3.1"}]},"date":"October 23, 2013","usn":"USN-2000-1","CVEs":["CVE-2013-2256","CVE-2013-4179","CVE-2013-4185","CVE-2013-4261","CVE-2013-4278"],"info":"nova vulnerabilities"}