{"update":{"12.04":[{"version":"3.2.3-0ubuntu3.5","package":"python3.2"},{"version":"3.2.3-0ubuntu3.5","package":"python3.2-minimal"}],"12.10":[{"package":"python3.2","version":"3.2.3-6ubuntu3.4"},{"version":"3.2.3-6ubuntu3.4","package":"python3.2-minimal"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","date":"October 01, 2013","threat":["An attacker could exploit this to cause Python to consume resources, resulting in a denial of service.","An attacker could exploit this to perform a man in the middle attack to view sensitive information or alter encrypted communications."],"usn":"USN-1984-1","CVEs":["CVE-2013-2099","CVE-2013-4238"],"info":"python3.2 vulnerabilities"}