{"update":{"14.04":[{"package":"python-django","version":"1.6.1-2ubuntu0.4"}],"10.04":[{"package":"python-django","version":"1.1.1-2ubuntu1.13"}],"12.04":[{"version":"1.3.1-4ubuntu1.12","package":"python-django"}]},"threat":["A remote attacker could use this issue to conduct phishing attacks.","A remote attacker could use this issue to cause Django to consume resources, resulting in a denial of service."],"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","CVEs":["CVE-2014-0480","CVE-2014-0481","CVE-2014-0482","CVE-2014-0483"],"info":"python-django vulnerabilities","usn":"USN-2347-1","date":"September 16, 2014"}