{"threat":["A remote attacker could possibly use this issue to cause Django to enter an infinite loop, resulting in a denial of service.","A remote attacker could possibly use this issue to perform a cross-site scripting attack."],"date":"March 23, 2015","info":"python-django vulnerabilities","CVEs":["CVE-2015-2316","CVE-2015-2317"],"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","update":{"10.04":[{"package":"python-django","version":"1.1.1-2ubuntu1.17"}],"14.04":[{"version":"1.6.1-2ubuntu0.8","package":"python-django"}],"12.04":[{"package":"python-django","version":"1.3.1-4ubuntu1.16"}],"14.10":[{"package":"python-django","version":"1.6.6-1ubuntu2.2"},{"package":"python3-django","version":"1.6.6-1ubuntu2.2"}]},"usn":"USN-2539-1"}