{"CVEs":["CVE-2015-5143","CVE-2015-5144"],"date":"July 09, 2015","info":"python-django vulnerabilities","threat":["A remote attacker could use this issue to cause a denial of service.","A remote attacker could use this issue to perform header injection attacks."],"usn":"USN-2671-1","update":{"14.10":[{"package":"python-django","version":"1.6.6-1ubuntu2.3"},{"version":"1.6.6-1ubuntu2.3","package":"python3-django"}],"12.04":[{"version":"1.3.1-4ubuntu1.17","package":"python-django"}],"14.04":[{"package":"python-django","version":"1.6.1-2ubuntu0.9"}],"15.04":[{"version":"1.7.6-1ubuntu2.1","package":"python-django"},{"package":"python3-django","version":"1.7.6-1ubuntu2.1"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes."}