{"threat":["A remote unauthenticated attacker could exploit this using the Cinder API to cause a denial of service via resource exhaustion."],"date":"February 21, 2013","info":"cinder vulnerability","CVEs":["CVE-2013-1664"],"update":{"12.10":[{"package":"python-cinder","version":"2012.2.1-0ubuntu1.1"}]},"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.","usn":"USN-1731-1"}