{"threat":["A remote attacker could exploit this to cause a denial of service via daemon outage.","A remote attacker could use this to obtain sensitive information or cause a denial of service via resource consumption."],"special":"The problem can be corrected by updating your system to the following package versions:\nIn general, a standard system update will make all the necessary changes.\nDaemons using the urllib or smtpd modules may also need to be restarted\nafter a pplying this update.","update":{"10.04":[{"version":"3.1.2-0ubuntu3.1","package":"python3.1-minimal"}],"11.04":[{"version":"3.1.3-1ubuntu1.1","package":"python3.1-minimal"},{"version":"3.2-1ubuntu1.1","package":"python3.2-minimal"}],"10.10":[{"version":"3.1.2+20100915-0ubuntu4.1","package":"python3.1-minimal"}]},"date":"December 19, 2011","info":"python3.1, python3.2 vulnerabilities","CVEs":["CVE-2010-3493","CVE-2011-1521"],"usn":"USN-1314-1"}